package net.vpndetector.data.model

import kotlinx.serialization.Serializable
import net.vpndetector.detect.Category
import net.vpndetector.detect.Check
import net.vpndetector.detect.Severity
import net.vpndetector.detect.Verdict
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

@Serializable
data class RunResult(
    val timestamp: Long,
    val tag: String = "",
    val checks: List<Check>,
    val verdict: Verdict,
) {
    /** Markdown-formatted plain-text report suitable for sharing. */
    fun toShareText(): String = buildString {
        val ts = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.US).format(Date(timestamp))
        appendLine("# vpn-detector run")
        appendLine()
        appendLine("- timestamp: $ts")
        if (tag.isNotEmpty()) appendLine("- tag: $tag")
        appendLine("- verdict: **${verdict.level}**")
        appendLine("- score: ${verdict.score}  (hard=${verdict.hardCount}, soft=${verdict.softCount})")
        appendLine("- methodology matrix: **${verdict.matrix}**")
        appendLine("  - geoip axis fired: ${verdict.matrixGeoip}")
        appendLine("  - direct axis fired: ${verdict.matrixDirect}")
        appendLine("  - indirect axis fired: ${verdict.matrixIndirect}")
        appendLine()

        for (cat in Category.values()) {
            val rows = checks.filter { it.category == cat }
            if (rows.isEmpty()) continue
            appendLine("## ${cat.name}")
            appendLine()
            for (c in rows) {
                appendLine("### [${c.severity.label()}] ${c.label}")
                appendLine("- value: ${c.value}")
                appendLine("- id: `${c.id}`")
                if (c.explanation.isNotBlank()) appendLine("- note: ${c.explanation}")
                if (c.details.isNotEmpty()) {
                    appendLine("- details:")
                    for (d in c.details) {
                        appendLine("  - [${d.verdict.label()}] ${d.source} → ${d.reported}")
                    }
                }
                appendLine()
            }
        }
        appendLine("---")
        appendLine("generated by vpn-detector-android")
    }

    private fun Severity.label(): String = when (this) {
        Severity.HARD -> "FAIL"
        Severity.SOFT -> "WARN"
        Severity.PASS -> "PASS"
        Severity.INFO -> "INFO"
    }
}
